# -*- coding: utf-8 -*-
"""BookingTicketsCLDLipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M0RkjzLc3JmMR2uccdvryA8pWkb1x4gJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

df = pd.read_csv('/content/booking.csv')

df

df.shape

df.info()

df.describe()

df.isnull().sum()

LE = LabelEncoder()

df['Booking_ID'] = LE.fit_transform(df['Booking_ID'])
df['type of meal'] = LE.fit_transform(df['type of meal'])
df['room type'] = LE.fit_transform(df['room type'])
df['market segment type'] = LE.fit_transform(df['market segment type'])
df['booking status'] = LE.fit_transform(df['booking status'])
df['date of reservation'] = LE.fit_transform(df['date of reservation'])

df.head(5)

df.groupby('booking status').mean()

X = df.drop(columns="booking status", axis=1)
Y =df['booking status']

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

print(X)

print(Y)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

import tensorflow as tf
tf.random.set_seed(3)
from tensorflow import keras

print(X.shape,X_train.shape,X_test.shape)

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(16,)),
    keras.layers.Dense(12,activation="relu"),
    keras.layers.Dense(2,activation="softmax")
])

model.compile(
    optimizer = "adam",
    loss = "sparse_categorical_crossentropy",
    metrics = ['accuracy']
)

history = model.fit(X_train_std,Y_train,validation_split=0.1,epochs=30)

plt.plot(history.history["accuracy"])
plt.plot(history.history["val_accuracy"])
plt.title("model accuracy")
plt.ylabel("accuracy")
plt.xlabel("epoch")

plt.legend(["training data","validation_data"], loc="lower right")

plt.plot(history.history["loss"])
plt.plot(history.history["val_loss"])
plt.title("model loss")
plt.xlabel("epoch")
plt.ylabel("loss")

plt.legend(["training data","validation data"], loc="lower right")

loss,accuracy = model.evaluate(X_test_std,Y_test)
print(accuracy)

print(X_test_std.shape)
print(X_test_std[0])

y_pred = model.predict(X_test_std)

print(y_pred.shape)
print(y_pred[0])

print(X_test_std)

print(y_pred)

input_data = (18095.880595,	1.813412,	0.096081,	0.773323,	2.113174,	0.496106,	0.041400,	0.686506,	58.933678,	3.487785,	0.037465,	0.032013,	0.227045,	99.932994,	0.758649,	275.537793,
)

input_data1 =np.asarray(input_data)

input_data_reshaped = input_data1.reshape(1,-1)

input_data_std = scaler.transform(input_data_reshaped)

prediction = model.predict(input_data_std)
print(prediction)

prediction_label = [np.argmax(prediction)]
print(prediction_label)

if prediction_label[0]==1:
  print("booking successfully")
else:
  print("Booking cancelled")

